### ISSUE TITLE
LUA error 3.2

### ISSUE THREAD

**Issue by keLston** [TekNoLogic/tekKompare#1]
Not entirely sure if this is a tekKompare issue or a bagnon issue. I tried the lua file dated July 09 as well.

Interface\FrameXML\GameTooltip.lua:126: StatLogicTooltipMoneyFrame1:SetPoint(): Couldn't find region named 'StatLogicTooltipTextLeft11':
Interface\FrameXML\GameTooltip.lua:126: in function `SetTooltipMoney':
Interface\FrameXML\GameTooltip.lua:88: in function`GameTooltip_OnTooltipAddMoney':
<string>:"_:OnTooltipAddMoney":1: in function <[string "_:OnTooltipAddMoney"]:1>
<in C code>: in function `SetHyperlink'
LibStatLogic-1.1-52:12346: in function`GetSum'
RatingBuster-1.4.4 (r$Revision: 226 $)\RatingBuster.lua:2254: in function `handler'
LibTipHooker-1.1-2:193: in function <...ingBuster\libs\LibTipHooker-1.1\LibTipHooker-1.1.lua:187>
<in C code>: in function`SetHyperlinkCompareItem'
tekKompare-3.0.3.5\tekKompare.lua:14: in function <Interface\AddOns\tekKompare\tekKompare.lua:7>
tekKompare-3.0.3.5\tekKompare.lua:41: in function <Interface\AddOns\tekKompare\tekKompare.lua:37>
<in C code>: ?
Informant-5.5.4293\Libs\LibExtraTip\LibExtraTip.lua:280: in function <...ce\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:276>
<in C code>: ?
<in C code>: ?
<in C code>: ?
<in C code>: ?
Informant-5.5.4293\Libs\LibExtraTip\LibExtraTip.lua:252: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:743: in function`ContainerFrameItemButton_OnEnter':
Bagnon-2.9.2\components\item.lua:215: in function <Interface\AddOns\Bagnon\components\item.lua:197>

**Comment by tekkub** [comment]
That's a nice mess of hooking going on there (thanks ratingsbuster and informant)... but I'd guess the issue is in StatLogic as that's the tooltip throwing the error
