### ISSUE TITLE
Battlepet hover tooltips

### ISSUE THREAD

**Issue by ckaotik** [TekNoLogic/tekKompare#10]
Hi tekkub,

I'd love to see Battlepet tooltips when hovering those links in chat. Unfortunately, Blizzard had to created a whole new concept for those :(

I noticed you like your code clean and simple (which I love) so I'll just suggest my sluggish hackish attempt in here, rather than a pull request.

```
local linktype, data = link:match("^([^:]+):?([^|]*)")
<snip>
elseif linktype and linktype == "battlepet" then
    data = { strsplit(":", data) }
    for k,v in pairs(data) do
        data[k] = tonumber(v)
    end
    BattlePetToolTip_Show(unpack(data))
end
```

on enter and 

```
BattlePetTooltip:Hide() 
```

on leave would do the trick.

**Comment by tekkub** [comment]
:bear: :heart: :paw_prints:

**Comment by ckaotik** [comment]
Thanks for the update, however, the include path in tekkompare.toc is incorrect :) 
It should be externals/tonumber_all.lua and is currently missing the externals subfolder.

**Comment by tekkub** [comment]
DERP!
