### ISSUE TITLE
Comparison tooltips closing on mouse out

### ISSUE THREAD

**Issue by cremor** [TekNoLogic/tekKompare#3]
Using 3.2.0.6-Beta, if you open a tooltip from chat (hoverlinks disabled), move the cursor into the main tooltip and then either move the cursor out again or move it over the close button, the comparison tooltips are closed.
Also happens if tekKompare is the only active Addon.

**Comment by tekkub** [comment]
Don't let ItemRefTooltip fuck with the compare tips

Closed by c4a3af703860331b0561770ffa9b08da52c9bbd7
