### ISSUE TITLE
Tooltip overlapping

### ISSUE THREAD

**Issue by cremor** [TekNoLogic/tekKompare#4]
Using 3.2.0.6-Beta, if you hover over an item in you bag so that the comparison tooltip fits neither on the left side nor on the right side into the screen, the tooltips are overlapping.
Example: http://img19.imageshack.us/img19/9030/wowscrnshot081709225239.jpg
(Also happens if tekKompare is the only active Addon.)

I once had a tooltip comparison Addon (sadly forgot the name) that moved the main tooltip a bit in that cases so the tooltips didn't overlap. Would be good if tekKompare could do this too.

**Comment by tekkub** [comment]
If you disable tK and use the default compare tips, does they not do this?

**Comment by cremor** [comment]
Ah, good question. It was the default interface :)
If I press Shift to get the comparison tooltip, the main tooltip is moved.
So tekKompare should support this for sure ;)

**Comment by tekkub** [comment]
I'm switching to blizzy's code in the next version, so everything should act exactly the same, except that tips are always shown, not just when shift is held.

**Comment by HunterZ** [comment]
I wonder if that would fix Issue #6.
