### ISSUE TITLE
Gems and Socket Bonuses

### ISSUE THREAD

**Issue by IrishPrime** [TekNoLogic/tekKompare#5]
Not sure if this is a bug so much as a feature that hasn't been added that I think would be helpful. I very much support the decision to not take enchants into account since comparing a new item will obviously be behind by whatever enchant is on the current item and the new item will eventually get the same enchant.

However, when comparing a new item (without sockets) to an equipped item (with gems and a socket bonus), I think those stats should be taken into consideration because the new item simply cannot gain those stats.

I guess this may largely be a limitation of the Blizzard UI and/or beyond the scope of the addon, but I think it would be nice.

**Comment by tekkub** [comment]
... tK doesn't do anything but show the tooltips, if there's data missing from them, you'll have to take that up with Blizzy.

**Comment by IrishPrime** [comment]
I figured it was a Blizzard UI limitation, sorry to trouble you with it.
