### ISSUE TITLE
Compare tooltips display improperly for items on action bar when game tooltip is anchored to mouse

### ISSUE THREAD

**Issue by HunterZ** [TekNoLogic/tekKompare#6]
See here for details, including a screenshot:
http://www.wowinterface.com/portal.php?id=275&a=viewbug&bugid=5439

According to her most recent comment on that page, Seerah was able to replicate it without any tooltip addon running by issuing a Lua command to anchor the cursor to the mouse.

Note also that both compare frames are corrupted when hovering over a ring/trinket/etc.

**Comment by tekkub** [comment]
As I told Seerah, I have never been able to reproduce this issue

**Comment by HunterZ** [comment]
Well myself, another user, and Seerah were all able to replicate it in the bug report thread that I linked so you may want to take a look at the info there if you haven't already.

For now I'm using Moncai Compare along with just the HoverTips part of tekKompare and it seems to work just fine. You may want to look at what Moncai Compare is doing differently, as it seems to have even less code if anything than tekKompare does.
