### ISSUE TITLE
Item Tooltips Display Incorrect Vendor Values

### ISSUE THREAD

**Issue by KestrelsAerie** [TekNoLogic/tekKompare#7]
When TekKompare is enabled, all vendor values for items are hugely inflated. For example, an item valued at (and vendored for) 5s47c showed a vendor value of over 21gold. I narrowed it down to TekKompare by disabling all addons, then re-enabling until the error appeared.

**Comment by tekkub** [comment]
and does this happen with ONLY tk enabled?

**Comment by KestrelsAerie** [comment]
Was just about to update: Installed Moncai's Equip Compare, and got the same behavior. I disabled that, and used the standard Blizzard Shift-Click. What happens is, the displayed vendor value is the value of EQUIPPED items! Very, very strange. Could be there is another add-on affecting this more subtly; with as many addons as I run, I'm not going to spend a lot of time trying to nail it down now. At least now I know where the weird values are coming from!

**Comment by KestrelsAerie** [comment]
Just to clarify, with an example: I have an off-hand dagger on my rogue with a value of 20g4s. Comparing to a cheap reward off-hand (doing low-level quests for rep), which has an actual value of 5s47c, your addon, Moncai's, and shift-click (no compare add-on enabled) show the value of the low-level item to be the same as my equipped off-hand.
