### ISSUE TITLE
Lua error in 3.3.0.7-Release

### ISSUE THREAD

**Issue by cremor** [TekNoLogic/tekKompare#8]
I'm getting this error when I click an item link and then move the tooltip. After that, the comparison window hides and never shows again.

tekKompare-3.3.0.7\tekKompare.lua:28: attempt to call global 'SetTips' (a nil value)

Seems like the whole function is missing in the file.

**Comment by tekkub** [comment]
Forgot about moving the itemref tooltip

Closed by 093151689d1fd2d511179009f28294a129beb32e
